NUMERATOR:

  PUSH(FP);
  MOV(FP, SP);

  MOV(R0, FPARG(2));
  CMP(IND(R0), T_FRACTION);
  JUMP_EQ(NUMERATOR_OF_FRAC);
  
  MOV(R0, INDD(R0,1));
  PUSH(R0);
  CALL(MAKE_SOB_INTEGER);
  DROP(1);
  POP(FP);
  RETURN;

NUMERATOR_OF_FRAC:
  MOV(R0, INDD(R0, 2));
  PUSH(R0);
  CALL(MAKE_SOB_INTEGER);
  DROP(1);
  POP(FP);
  RETURN;