PLUS:
  PUSH(FP);
  MOV(FP, SP);
  PUSH(R1);
  PUSH(R2);
  PUSH(R3);
  PUSH(R4);
  PUSH(R5);
  PUSH(R10);
  PUSH(R11);
  PUSH(R12);
  PUSH(R13);


  PUSH(1);
  PUSH(0);
  PUSH(1);
  CALL(MAKE_SOB_FRACTION);
  DROP(3);
  MOV(R1, R0);
  MOV(R5, FPARG(1)); 
  MOV(R3, 0); 
PLUS_LOOP:
  CMP(R5, R3);
  JUMP_EQ(PRE_PLUS_END);
  MOV(R4, FPARG(R3 + 2)); 
  CMP(IND(R4), T_FRACTION);
  JUMP_EQ(PLUS_WITH_FRACTION);
  MOV(R2, INDD(R4, 1));
  PUSH(1);
  PUSH(R2);
  PUSH(1);
  CALL(MAKE_SOB_FRACTION);
  DROP(3);
  MOV(R4, R0);

PLUS_WITH_FRACTION:
  PUSH(R1);
  PUSH(R4);
  CALL(PLUS_FRACS);
  DROP(2);
  MOV(R1, R0);
  ADD(R3, 1);
  JUMP(PLUS_LOOP);

PRE_PLUS_END:
  MOV(R0, R1);
  CMP(INDD(R0, 3), 1); 
  JUMP_NE(RETURN_FRACTION);
  PUSH(INDD(R0, 2));
  CALL(MAKE_SOB_INTEGER);
  DROP(1); 
  JUMP(PLUS_END);

RETURN_FRACTION:
  CMP(INDD(R0, 2), 0);
  JUMP_NE(TRY_TO_REDUCE);
  PUSH(0);
  CALL(MAKE_SOB_INTEGER);
  DROP(1);
  JUMP(PLUS_END);

TRY_TO_REDUCE:

  MOV(R12, INDD(R0,2));
  MOV(R13, INDD(R0,3));
  REM(R12, R13);
  CMP(R12, 0);
  JUMP_NE(PLUS_TRY_TO_REDUCE);
  MOV(R12, INDD(R0,2));
  DIV(R12, R13);
  MOV(R0, R12);
  PUSH(R0);
  CALL(MAKE_SOB_INTEGER);
  DROP(1);
  JUMP(PLUS_END);

PLUS_TRY_TO_REDUCE:
  
  MOV(R10, R0);
  PUSH(INDD(R0, 2));
  PUSH(INDD(R0, 3));
  CALL(GCD);
  DROP(2);
  
  MOV(R11, INDD(R10, 2));
  MOV(R12, INDD(R10, 3));
  DIV(R11, R0);
  DIV(R12, R0);

  PUSH(1);
  PUSH(R11);
  PUSH(R12);
  CALL(MAKE_SOB_FRACTION);
  DROP(3);


PLUS_END:
  POP(R13);
  POP(R12);
  POP(R11);
  POP(R10);
  POP(R5);
  POP(R4);
  POP(R3);
  POP(R2);
  POP(R1);
  POP(FP);
  RETURN;
