EQUAL_MATH:
  PUSH(FP);
  MOV(FP, SP);
  PUSH(R1);
  PUSH(R2);
  PUSH(R3);

  MOV(R2, FPARG(1));
  MOV(R3, IMM(3));
  MOV(R0,FPARG(2));
  MOV(R0,INDD(R0,1));

EQUAL_MATH_LOOP:
  CMP(R2, IMM(1));
  JUMP_EQ(EQUAL_MATH_RETURN_TRUE);
  MOV(R1, FPARG(R3));
  MOV(R1, INDD(R1,1));
  CMP(R0,R1);
  JUMP_NE(EQUAL_MATH_RETURN_FALSE);
  SUB(R2,IMM(1));
  ADD(R3,IMM(1));
  JUMP(EQUAL_MATH_LOOP);

EQUAL_MATH_RETURN_FALSE:
  MOV(R0,IMM(SOB_BOOL_FALSE));
  JUMP(EQUAL_MATH_END);

EQUAL_MATH_RETURN_TRUE:
  MOV(R0,IMM(SOB_BOOL_TRUE));

EQUAL_MATH_END:
  POP(R3);
  POP(R2);
  POP(R1);
  POP(FP);
  RETURN;
