NOT:
  PUSH(FP);
  MOV(FP, SP);
  MOV(R0, FPARG(2));

  CMP(IND(R0), T_BOOL);
  JUMP_NE(RETURN_FALSE);

  CMP(R0, IMM(SOB_BOOL_FALSE));
  JUMP_EQ(NOT_RETURN_TRUE);

NOT_RETURN_FALSE:
  MOV(R0,IMM(SOB_BOOL_FALSE));
  POP(FP);
  RETURN;

NOT_RETURN_TRUE:
  MOV(R0,IMM(SOB_BOOL_TRUE));
  POP(FP);
  RETURN;