
STRING_TO_SYMBOL:
	PUSH(FP);
	MOV(FP, SP);
	PUSH(R1);
	PUSH(R2);
	PUSH(R3);
	PUSH(R4);
	PUSH(R5);
	PUSH(R6);

	MOV(R2, IND(SOB_SYM_LIST));
	MOV(R4, FPARG(2));		
	
STS_TO_SYMBOL_LOOP:
	CMP(R2, SOB_NIL);
	JUMP_EQ(STS_SYMBOL_NOT_FOUND);

	MOV(R3, INDD(R2, 1));	
  MOV(R3, INDD(R3, 1)); 	

	CMP(INDD(R4, 1), INDD(R3, 1));
	JUMP_NE(STS_CMP_NEXT);
  	
	MOV(R5, INDD(R4, IMM(1)));
	ADD(R5, 1);

STS_COMPARE_LOOP:
	CMP(R5, IMM(1)); 
	JUMP_EQ(STS_FOUND);

	CMP(INDD(R4, R5), INDD(R3, R5));
	JUMP_NE(STS_CMP_NEXT);

	SUB(R5, 1);
	JUMP(STS_COMPARE_LOOP);

STS_CMP_DONE_AND_NOT_MATCH:

STS_CMP_NEXT:
	MOV(R6, INDD(R2,2));
	MOV(R2, R6);
	JUMP(STS_TO_SYMBOL_LOOP);

STS_FOUND:
	MOV(R0, INDD(R2, 1));
	JUMP(DONE_STS_TO_SYM);

STS_SYMBOL_NOT_FOUND:
	PUSH(R4); 
	CALL(MAKE_SOB_SYMBOL);
	DROP(1);
	MOV(R1, R0); 

	PUSH(IND(SOB_SYM_LIST));
	PUSH(R1);
	CALL(MAKE_SOB_PAIR);
	DROP(2);
	MOV(IND(SOB_SYM_LIST), R0);
	MOV(R0, R1);

DONE_STS_TO_SYM:
	POP(R6);
	POP(R5);
	POP(R4);
	POP(R3);
	POP(R2);
	POP(R1);
	POP(FP);
	RETURN;
